# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.20'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@7.3.7
    npm install
    ng build --prod
  displayName: 'npm install and build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'