export class StudentProfile {
  public id: any;
  public firstName: any;
  public lastName: any;
  public gender: any;
  public dob: any;
  public maritalStatus: any;
  public email: any;
  public mobile: any;
  public whatsappNumber: any;
  public password: any;
  public confirmPassword: any;
  public isGraduated: any;
  public stateId: any;
  public stateName: any;
  public collegeCity: any;
  public collegeName: any;
  public aadharNumber: any;
  public panNumber: any;
  public educationalQualification: any;
  public graduationPassingYear: any;
  public subject: any;
  public profession: any;
  public currentLocation: any;
  public gttId: any;
  public roleId: any;
  public isPlaced: any;
  public vaccinationStatus: any;
  public termsAndConditions: any;
  public caste: any;
  public candidateCategory: any;
  public placedOrganization: any;
  public designation: any;
  public joiningMonth: any;

  public disabilityType: any;
  public disabilityPercent: any;
  public percentageMarks: any;
  public languageKnown: any;

  public isExperience: any;
  public experienceYears: any;
  public employer1: any;
  public employer2: any;
  public alternateNumber: any;
  public fatherName: any;
  public motherName: any;
  public guardianName: any;
  public pincode: any;
  public postgraduationPassingyear: any;
  public postgraduationInstitution: any;
  public pursuingPostGraduate: any;
  public postqraduationQualification: any;
  public postalAddress: any;
  public vaccinationcertificatefilename: any;
  public uploadVaccinationCertificate: any;
  public active: any;
  constructor() {}
}
