export class UserManagement {
    constructor(        
    public firstName : string,
    public lastName : string,
    public gender : string,
    public dob : string,
    public maritalStatus : string,
    public email : string,
    public mobile : string,
    public whatsappNumber : string,
    public password : string,
    public confirmPassword : string,
    public isGraduated : string,
    public collegeCity : string,
    public academiciInstitutionName : string,
    public aadharNumber : string,
    public panNumber : string,
    public educationalQualification : string,
    public graduationPassingYear : string,
    public subject : string,
    public profession : string,
    public currentLocation : string,
    public isPlaced : string,
    public gttId:any,
    public vaccinationStatus: string,
    public termsAndConditions: string,
    public postalAddress:any,
    public pursuingPostGraduate: any,
    public postGraduationPassingYear:string,
    public postGraduationInstitution:string,
    public postGraduationQualification:string,
    public alternateNumber: string,
    public fathersName:string,
    public motherName:string,
    public guardiansName:string,
    public pincode:any,
    public disabilityType: string,
    public disabilityPercent: string,
    public percentageMarks: string,
    public languageKnown: string,
    public isExperience: string,
    public experienceYears: string,
    public employer1: string,
    public employer2: string,
    public caste: string,
    public candidateCategory: string,
    public placedOrganization: string,
    public designation: string,
    public joiningMonth: string,
    public uploadVaccinationCertificate: string,
    
    
    ){}
}
